---
abstract: parse text into an array of tokens or array of arrays
author:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
build_requires:
  Scalar::Util: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ParseWords
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
resources:
  repository: http://github.com/chorny/Text-ParseWords
version: 3.28
