---
abstract: 'Mark modules as loaded/unloaded'
author:
  - 'Jos Boumans <kane[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Loaded
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
resources:
  repository: https://github.com/jib/module-loaded
version: 0.08
