--- #YAML:1.0
name:               Socket
version:            2.009
abstract:           networking constants and support functions
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::CBuilder:  0
    ExtUtils::Constant:  0.23
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006001
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
