--- #YAML:1.0
name:                Term-Cap
version:             1.12
abstract:            Perl termcap interface
license:             ~
author:              
    - Jonathan Stowe <gellyfish@gellyfish.com>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
    Test::More:                    0.33
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
