---
abstract: 'Generic archive extracting mechanism'
author:
  - 'Jos Boumans <kane[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archive-Extract
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 0
  File::Path: 0
  File::Spec: 0.82
  IPC::Cmd: 0.64
  Locale::Maketext::Simple: 0
  Module::Load::Conditional: 0.04
  Params::Check: 0.07
  Test::More: 0
  if: 0
resources:
  repository: https://github.com/jib/archive-extract
version: 0.68
