--- 
abstract: Warn on implicit encoding conversions
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: encoding-warnings
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.7.0
version: 0.11
