---
abstract: 'Perl lint'
author:
  - 'Joshua ben Jore <jjore@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Lint
no_index:
  directory:
    - t
    - inc
requires:
  Module::Pluggable: 0
  Test::More: 0
  if: 0
version: 1.17
