---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Complex
no_index:
  directory:
    - t
    - inc
requires:
  Config: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  Scalar::Util: 1.11
  Test::More: 0
  overload: 0
  strict: 0
  warnings: 0
version: 1.59
