---
abstract: 'Templated based param validation'
author:
  - 'Jos Boumans <kane[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Check
no_index:
  directory:
    - t
    - inc
requires:
  Locale::Maketext::Simple: 0
  Test::More: 0
resources:
  repository: https://github.com/jib/params-check
version: 0.36
