---
abstract: 'efficiently compute time from local and GMT time'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  POSIX: 0
  Test::More: 0.88
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Local
requires:
  Carp: 0
  Config: 0
  Exporter: 0
  constant: 0
  strict: 0
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Time-Local
  repository: git://git.urth.org/Time-Local.git
version: 1.2300
