---
abstract: 'Convert Pod data to formatted Latex'
author:
  - 'Tim Jenness <tjenness@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-LaTeX
provides:
  Pod::LaTeX:
    file: lib/Pod/LaTeX.pm
    version: 0.61
requires:
  Pod::Find: 0
  Pod::ParseUtils: 0.3
  Pod::Parser: 0
  Pod::Select: 0
  if: 0
resources:
  homepage: http://github.com/timj/perl-Pod-LaTeX/tree/master
  license: http://dev.perl.org/licenses/
  repository: git://github.com/timj/perl-Pod-LaTeX.git
version: 0.61
