---
abstract: unknown
author:
  - unknown
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI.pm
no_index:
  directory:
    - t
    - inc
    - t
requires:
  FCGI: 0.67
  File::Spec: 0.82
  Test::More: 0.98
  perl: 5.006000
resources:
  repository: http://github.com/markstos/CGI.pm/tree/master
version: 3.63
